### ISSUE TITLE
form for data entry

### ISSUE THREAD

**Issue by organizejs** [collective-action/tech#11]
not needed for now, but nice to have in the future. scoping/design can happen now.

**Comment by bentarnoff** [comment]
this might help: https://staticman.net/

**Comment by organizejs** [comment]
cool this is awesome

**Comment by jbranchaud** [comment]
What about setting up a Google Form that automatically submits a GitHub issue. It seems like that might fit in with your existing workflow. https://medium.com/@01010111/using-google-forms-to-submit-github-issues-efdb5f876b

**Comment by organizejs** [comment]
@jbranchaud love the idea, i'll see if i can get to it this weekend.

**Comment by organizejs** [comment]
@jbranchaud done! thanks for the tutorial 

https://docs.google.com/forms/d/e/1FAIpQLSc5ZQMAxo3nzWhcBN0xAv-wu1Tn2VaPMLTsHPioUmgmDJzP3Q/viewform
