### ISSUE TITLE
[Action] hong kong information technology workers union

### ISSUE THREAD

**Issue by organizejs** [collective-action/tech#251]
https://www.reuters.com/article/us-hongkong-protests-unions/hong-kong-workers-flock-to-labor-unions-as-new-protest-tactic-idUSKBN1Z9007

Programer Alex Tang said his newly formed, 280-member Hong Kong Information Technology Workers’ Union was developing a database of employers who would not threaten or dismiss staff for supporting protests.

**Comment by nataliyaned** [comment]
Is this live yet? I haven't been able to find it on their website, but I think it qualifies.

**Comment by organizejs** [comment]
i interviewed one of the founding members, and might publish something on lausan. so we'd be able to use that. but yeah, afaik, nothing more about this in english.
