### ISSUE TITLE
struggle categorization

### ISSUE THREAD

**Issue by organizejs** [collective-action/tech#255]
One thing i'm thinking about is whether or not our categories for struggle type is accurate enough. 

Take this one as a case-study: "A group of Googlers unhappy with the company's expanding 'need to know' restrictions on internal documents have come up with a clever form of protest: A new tool that sends auto alerts to Google's top lawyer every time an employee opens a company document.  "

This would typically be filed under 'working_conditions'. However, it feels not quite accurate in this case because these 'expanding 'need to know' restrictions' are an outcome of workers organizing (typically) around issues like military contracts, ICE, etc. 

I'm wondering if we should introduce another struggle type. not sure...

**Comment by nataliyaned** [comment]
We could add a tag like employee_privacy? 

I'm fine with keeping it as working_conditions but I do think there's a bigger trend behind this worth recognizing.
