### ISSUE TITLE
[Action] gig driver union conference

### ISSUE THREAD

**Issue by organizejs** [collective-action/tech#259]
https://twitter.com/IWGBunion/status/1222076308462718978?s=19

Should this one count? Exciting convening, but not really an "action"

**Comment by nataliyaned** [comment]
Very cool! Let's keep an eye out for this and publish when their Manifesto is out.

Sanjana wrote it up for Wired: https://www.wired.co.uk/article/gig-economy-uber-unions

**Comment by nataliyaned** [comment]
Also: https://iwgb.org.uk/post/5e2ff05f4b19a/first-ever-international-meeti
