### ISSUE TITLE
[Action] oracle employees protest trump fundraiser by ceo

### ISSUE THREAD

**Issue by organizejs** [collective-action/tech#268]
http://www.employeesforethics.com/blog/
https://www.change.org/p/larry-ellison-uphold-company-ethics
https://www.vox.com/recode/2020/2/13/21136577/larry-ellison-fundraiser-donald-trump-oracle-employees

**Comment by organizejs** [comment]
https://www.staradvertiser.com/2020/02/20/breaking-news/oracle-employees-protest-larry-ellisons-fundraiser-for-trump/

**Comment by nataliyaned** [comment]
#278
