### ISSUE TITLE
[April 17] Tell Amazon: Reinstate Fired Workers Organizing for Health and Safety Protections in Warehouses

### ISSUE THREAD

**Issue by organizejs** [collective-action/tech#354]
https://actionnetwork.org/petitions/tell-amazon-reinstate-fired-workers-organizing-for-health-and-safety-protections-in-warehouses

**Comment by organizejs** [comment]
@nataliyaned this is not really by 'tech workers' (even tho the organizing group is - Athena), should we include this?

**Comment by nataliyaned** [comment]
Leaning towards no
