### ISSUE TITLE
[April 21] Hundreds of Amazon Workers Are Not Going to Work in Nationwide Protest

### ISSUE THREAD

**Issue by organizejs** [collective-action/tech#359]
https://www.vice.com/amp/en_us/article/jge77g/hundreds-of-amazon-workers-are-not-going-to-work-in-nationwide-protest

https://thehill.com/policy/technology/493772-hundreds-of-amazon-workers-to-walk-off-starting-tuesday

**Comment by nataliyaned** [comment]
https://act.united4respect.org/onlineactions/AGiBsGSON06rBk_m8F6Zyg2
